# Generated by Django 5.1.5 on 2025-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_booking_id_booking_travelers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
