# Generated by Django 5.1.5 on 2025-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_paymenttransaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
