# Generated by Django 5.1.5 on 2025-03-28 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='raw_response',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr_codes/'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
