# Generated by Django 5.1.5 on 2025-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
