# Generated by Django 5.1.5 on 2025-03-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_paymenttransaction_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='myapp.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='tickets/qr_codes/'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='myapp_ticke_ticket__2ce595_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='myapp_ticke_status_0989ec_idx'),
        ),
    ]
