# Generated by Django 5.1.5 on 2025-03-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ticket_notes_ticket_payment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('premium', 'Premium')], default='general', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='myapp_payme_transac_3fc617_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='myapp_payme_status_3108e7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'created_at'], name='myapp_payme_user_id_79cd45_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking', 'issued_date'], name='myapp_ticke_booking_00de96_idx'),
        ),
    ]
