# Generated by Django 5.1.5 on 2025-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
